# Generated by Django 4.0.6 on 2022-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default='', max_length=20),
        ),
    ]
