# Generated by Django 4.0.6 on 2022-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meseros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(default='', max_length=20)),
                ('procedencia', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
